version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'coton_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3333:3306'
    volumes:
       # Where our data will be persisted
      - ./mysql:/var/lib/mysql

networks:
  coton-network: